---
title: "303-rewriting-example_fn"
author: ''
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 8, fig.width = 8, tidy=FALSE)
```

`r getwd()`  

Last knit was `r Sys.time()`

Copied from "209-2017-09-12-example-containing-exclusion_region.Rmd"

```{r}
library(gritsr2)
set.seed(1)
genotype_bim_original = genotype_bim_original[1:5, ]
params_example = params_example_fn(
  bim_original, genotype_bim_original, hotspot,
  NNN = 200,
  p_subset_genotype = .2,
  beta_causal_snps = .85,
  causal_snps = 3:5)
```


```{r}
example_fn = function(params_example){
  eee = larrys_example_genotype_etc_fn(params_example)
  names(eee)
  bim = eee$bim
  genotype = eee$genotype
  
  
  str(bim)
  str(genotype)
  eee$target_markers
  target_markers = intersect(eee$target_markers, dimnames(genotype)[[2]])
  target_markers
  g_target = genotype[, target_markers]
  Psi = Psi_fn(params_example, Psi_override = FALSE)
  fam = example_fam_fn(params_example, g_target)
  list(bim = bim,
       genotype = genotype,
       exclusion_region = exclusion_region,
       fam = fam,
       target_markers = target_markers,
       Psi = Psi)
}
```

