---
title: "04-sampling_set_fn"
author: ""
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 10, fig.width = 8, tidy=FALSE)
```

`r getwd()`  

"2017-09-14 08:12:36 PDT"

Last knit was `r Sys.time()`

```{r}
library(gatars)
bim = alternative_example$bim
epsilon_on_log_scale = 0.02
exclusion_region = alternative_example$exclusion_region
genotype = alternative_example$genotype
target_markers = alternative_example$target_markers[3:5]
params_sampling_set = params_sampling_set_fn(
  bim, epsilon_on_log_scale, exclusion_region,
  genotype, hotspot, target_markers)
names(params_sampling_set)
sampling_set = sampling_set_fn(params_sampling_set)
```


# Inside `sampling_set_fn`

```{r}
MMM = params_sampling_set$MMM
epsilon_on_log_scale = params_sampling_set$epsilon_on_log_scale
# p_target are the mafs of the target snps and the mafs we want to match
p_target = params_sampling_set$p_target
# Remove from bim and genotype the regions specified by exclusion_region
# The working files are then bim_with_target_and_exclusion_region_removed
# and genotype_with_stuff_removed.
# p_sim is the maf genotype_with_stuff_removed
bim_with_target_and_exclusion_regions_removed = 
  bim_with_target_and_exclusion_regions_removed_fn(params_sampling_set)
genotype_with_stuff_removed = genotype[, bim_with_target_and_exclusion_regions_removed$snp]
p_sim = unname(colMeans(genotype_with_stuff_removed)/2)
# For sampling_set I march through each mmm = 1, ...M, 
# for each mmm, I find the good_ones, the columns of genotype_with_stuff_removed
# whose mafs match.  
# I use epsilon_on_log_scale to parametrize the matching.
# Notice that if I get more than 1000 good ones, I sample to get at most 1000.
sampling_set = lapply(1:MMM, function(mmm){
  p_this = p_target[mmm]
  lower = p_this * (1 - epsilon_on_log_scale)
  upper = p_this * (1 + epsilon_on_log_scale)
  good_ones_q = (lower < p_sim & p_sim < upper)
  good_ones = which(good_ones_q)
  N_good_ones = length(good_ones)
  if(N_good_ones > 1000){
    good_ones = sort(sample(good_ones, 1000))
  }
  answer =  genotype_with_stuff_removed[, good_ones, drop = FALSE]
  answer
})
# report tells me how many good ones I got in each sampling set.
report = do.call(rbind, lapply(1:MMM, function(mmm){
  this_genotype = sampling_set[[mmm]]
  p_sim = unname(colMeans(this_genotype)/2)
  data.frame(min = round(min(p_sim), 5),
             p_target = round(p_target[mmm], 5),
             max = round(max(p_sim), 5),
             set_size = ncol(this_genotype))
}))
rownames(report) = NULL
report
list(
  params_sampling_set = params_sampling_set,
  report = report,
  sampling_set = sampling_set)
```

