---
title: "06-independent_segment_fn"
author: ""
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 10, fig.width = 8, tidy=FALSE)
```

`r getwd()`  

"2017-09-14 08:12:36 PDT"

Last knit was `r Sys.time()`

```{r}
library(gatars)
bim = alternative_example$bim
chromosome = 21
independent_segment_fn_answer = independent_segment_fn(bim, chromosome, hotspot)
length(independent_segment_fn_answer)
head(independent_segment_fn_answer)
head(bim)
```


```{r}
chromosome = 21
bim_this_chromosome = bim[bim$chromosome == chromosome, ]
str(bim_this_chromosome)
hot = hotspot_this_chromosome = hotspot[hotspot$chromosome == chromosome, ]
str(hot)
# bim_just_these removes snps that are inside hotspots
bim_just_these = bim_this_chromosome[!sapply(bim_this_chromosome$bp, function(this){
  any(hot$start <= this & this <= hot$end)
}), ]
str(bim_just_these)
bp = bim_just_these$bp
# hot_just_these removes head and tail rows that do no cutting
hot_just_these = hot[bp[1] <= hot$center & hot$center <= bp[length(bp)], ]
str(hot_just_these)
center = hot_just_these$center
# bp_index is the index of the last snp left of this hot$center
# Saying it with more details, for each center of a hotspot, 
# give me the index of the bp immediately to the center's left.
# Repeats indicate that there were no bp's between hotspots.
bp_index = sapply(center, function(this){
  max(which(bp < this))
})
str(bp_index)
# breaks will be used to separate the bp index numbers
# segments is the answer
breaks = unique(bp_index)
breaks
numbers = 1:length(bp)
breaks_with_ends = unique(c(0, breaks, max(numbers)))
left = breaks_with_ends[-length(breaks_with_ends)]
right = breaks_with_ends[-1]
segment_numbers = lapply(1:length(left), function(kkk){
  numbers[left[kkk] < numbers & numbers <= right[kkk]]
})
head(segment_numbers)
segments = lapply(segment_numbers, function(this){
  bim_just_these[this, ]
})
head(segments)
head(center, 40)
independent_segment_0_fn_answer = segments
```

