---
title: "18-differences-between-davies_not_lu-and-basic_and_optimized"
author: ""
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 10, fig.width = 8, tidy=FALSE)
```

`r getwd()`  

"2017-09-27 06:09:43 PDT"

Last knit was `r Sys.time()`

```{r}
library(gatars)
keeper = c(1:12, 101:112)
bim = alternative_example$bim
genotype = alternative_example$genotype[keeper, ]
fam = alternative_example$fam[keeper, ]
target_markers = alternative_example$target_markers[c(3, 5)]
Psi = alternative_example$Psi[keeper, keeper]
exclusion_region = alternative_example$exclusion_region
genotype_target_markers = genotype[, target_markers]
set.seed(2)
epsilon_on_log_scale = 0.2
sampling_set = gatars_sampling_set(
    bim, epsilon_on_log_scale, exclusion_region,
    genotype, hotspot, target_markers)
print(sampling_set)

N_sim_reps = 10
# gatars(fam, Psi, sampling_set, N_sim_reps = 10)
params_sampling_set = sampling_set$params_sampling_set
sampling_set = sampling_set$sampling_set
weights = NULL
params = params_fn(params_sampling_set, fam, Psi, sampling_set, N_sim_reps, weights)
# ooo = one_experiment_fn(params, calculate_optimized = TRUE)
# ooo$p_value
# inside one_experiment_fn
calculate_optimized = TRUE
theta_init = params$theta_init
g_target = params$g_target
library(Matrix)
rankMatrix(g_target)
```


# function definitions

```{r}
AAA_fn = function(alpha_B, alpha_S, alpha_T, MMM){
  III = diag(rep(1, MMM))
  JJJ = matrix(rep(1, MMM * MMM), nrow = MMM)
  A_1 = alpha_B * JJJ + (alpha_S + alpha_T) * III
  A_2 = -(alpha_B * JJJ + alpha_S * III)
  A_3 = alpha_B * JJJ + (alpha_S - alpha_T) * III
  AAA = rbind(cbind(A_1, A_2),
              cbind(A_2, A_3))
  AAA
}
zzz_etc_fn = function(g_target, Phi, WWW, y_1, y_2){
  z_1 = as.vector(WWW %*% t(g_target) %*% y_1)
  z_2 = as.vector(WWW %*% t(g_target) %*% y_2)
  zzz = c(z_1, z_2)
  
  e_g_target_1 = colMeans(g_target)
  e_g_target = matrix(rep(e_g_target_1, nrow(g_target)), nrow = nrow(g_target), byrow = TRUE)
  e_z_1 = matrix(as.vector(WWW %*% t(e_g_target) %*% y_1), ncol = 1)
  e_z_2 = matrix(as.vector(WWW %*% t(e_g_target) %*% y_2), ncol = 1)
  mu_z = rbind(e_z_1, e_z_2)
  
  V_G = cov(g_target)
  W_VG_W = WWW %*% V_G %*% WWW
  V_z = kronecker(Phi, W_VG_W)
  
  list(zzz = zzz,
       mu_z = mu_z,
       V_z = V_z)
}
```

# `uno_experimento_fn`

```{r}
calculate_optimized = TRUE
adaptive_conf_level = params$adaptive_conf_level
g_target = params$g_target
MMM = params$MMM
N_sim_reps_interval = params$N_sim_reps_interval
N_sim_reps_limit = params$N_sim_reps_interval
WWW = params$WWW
y_1 = params$yyy
y_2 = params$e_y
rho_uni = params$rho_uni
Phi = params$Phi
test_size = params$test_size

zzz_etc = zzz_etc_fn(g_target, Phi, WWW, y_1, y_2)
zzz = zzz_etc$zzz
mu_z = zzz_etc$mu_z
V_z = zzz_etc$V_z
# -------------------------------------------------- alpha_uni
alpha_uni_zero = expand.grid(
  B = rho_uni, 
  S = rho_uni, 
  T = rho_uni)
alpha_uni_zero_sum = apply(alpha_uni_zero, 1, sum)
alpha_uni = alpha_uni_zero[alpha_uni_zero_sum == 1, ]
str(alpha_uni)
row.names(alpha_uni) = NULL
look = alpha_uni[apply(alpha_uni, 1, function(row){
  sum(row == 0) > 1
}), ]
# -------------------------------------------------- basic_AAA
# basic_ones = c(10, 65, 279)
# look = alpha_uni[basic_ones, ]
# MMM = ncol(g_target)
# AAA_basic = lapply(basic_ones, function(jjj){
#   alpha = alpha_uni[jjj, ]
#   AAA = AAA_fn(alpha$B, alpha$S, alpha$T, MMM)
#   list(alpha = alpha, AAA = AAA)
# })
# ------------------------------------------------ df contains 
# ----------------------B, S, T (the three components of alpha
# ----------------------- as well as  q, and (nominal) p_value
df = do.call(rbind, lapply(1:nrow(alpha_uni), function(jjj){
  alpha = alpha_uni[jjj, ]
  AAA = AAA_fn(alpha$B, alpha$S, alpha$T, MMM)
  davies_answer = davies_fn(zzz, mu_z, V_z, AAA)
  cbind(alpha, davies_answer)
}))
str(df)

# ------------------------- basic is a data.frame that contains 
# ------------------------ the quadratic form q and the p-value 
# ----------------------- of the three basic statistics B, S, T
basic = rbind(df[df$B == 1, ],
              df[df$S == 1, ],
              df[df$T == 1, ])
rownames(basic) =  c("B", "S", "T")
# --------------------- optimized is a data.frame that contains
# ------------ the quadratic form q, the nominal p-value, and x
# ----------------- of the optimized statistics BS, BT, ST, BST
bs_0 = df[df$B + df$S == 1, ]
bt_0 = df[df$B + df$T == 1, ]
st_0 = df[df$S + df$T == 1, ]
bs = bs_0[which.min(bs_0$p_value), ]
bt = bt_0[which.min(bt_0$p_value), ]
st = st_0[which.min(st_0$p_value), ]
bst = df[which.min(df$p_value), ] 
optimized = rbind(bs, bt, st, bst)
xxx = unlist(lapply(optimized$p_value, q_alice_fn))
optimized$x = xxx
rownames(optimized) =  c("BS", "BT", "ST", "BST")
#------------------------------------------------------- output
p_value_basic = basic$p_value
names(p_value_basic) = rownames(basic)
p_value_basic

q_basic = basic$q
names(q_basic) = rownames(basic)
q_basic

q_optimized = optimized$q
names(q_optimized) = rownames(optimized)
q_optimized

names(xxx) = rownames(optimized)
list(
  basic = basic,
  optimized = optimized,
  p_value_basic = p_value_basic,
  q_basic = q_basic,
  q_optimized = q_optimized,
  xxx = xxx)

```


# `one_experiment_fn`

```{r}
g_target = params$g_target
MMM = params$MMM
WWW = params$WWW
www = params$www
y_1 = params$yyy
y_2 = params$e_y
rho_uni = params$rho_uni
Phi = params$Phi

JJJ = matrix(rep(1, MMM * MMM), nrow = MMM)
III = diag(rep(1, MMM))
zero_M = matrix(rep(0, MMM * MMM), nrow = MMM)
zero_M_2M = matrix(rep(0, MMM * 2 * MMM), nrow = MMM)
z_1 = as.vector(WWW %*% t(g_target) %*% y_1)
z_2 = as.vector(WWW %*% t(g_target) %*% y_2)
zzz = c(z_1, z_2)
e_g_target_1 = colMeans(g_target)
e_g_target = matrix(rep(e_g_target_1, nrow(g_target)), nrow = nrow(g_target), byrow = TRUE)
e_z_1 = matrix(as.vector(WWW %*% t(e_g_target) %*% y_1), ncol = 1)
e_z_2 = matrix(as.vector(WWW %*% t(e_g_target) %*% y_2), ncol = 1)
mu_z = rbind(e_z_1, e_z_2)
V_G = cov(g_target)
W_VG_W = WWW %*% V_G %*% WWW
V_z = kronecker(Phi, W_VG_W)
# ----------------------------------------------- straight, fancy_grid
alpha_uni_zero = expand.grid(a1 = rho_uni, a2 = rho_uni, a3 = rho_uni)
alpha_uni = alpha_uni_zero[apply(alpha_uni_zero, 1, sum) <= 1, ]
answer_0 = do.call(rbind, lapply(1:nrow(alpha_uni), function(jjj){
  alpha = alpha_uni[jjj, ]
  a4 = (1 - sum(as.vector(alpha)))
  A_1 = alpha[, 1] * JJJ + alpha[,2] * III
  A_2 = alpha[, 3] * JJJ + a4 * III
  AAA =  rbind(cbind(A_1 + A_2, -A_1),
               cbind(-A_1, A_1 - A_2))
  davies_answer = davies_fn(zzz, mu_z, V_z, AAA)
  cbind(alpha, a4, davies_answer)
}))
str(answer_0)
```

```{r}
alpha_uni
```








