---
title: "22-uno_experimento_fn-inside-gatars"
author: ""
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 10, fig.width = 8, tidy=FALSE)
```

`r getwd()`  

"2017-09-26 11:06:13 PDT"

Last knit was `r Sys.time()`

```{r}
library(gatars)
keeper = c(1:12, 101:112)
bim = alternative_example$bim
genotype = alternative_example$genotype[keeper, ]
fam = alternative_example$fam[keeper, ]
target_markers = alternative_example$target_markers[c(3, 5)]
Psi = alternative_example$Psi[keeper, keeper]
exclusion_region = alternative_example$exclusion_region
genotype_target_markers = genotype[, target_markers]
set.seed(2)
epsilon_on_log_scale = 0.2
sampling_set = gatars_sampling_set(
    bim, epsilon_on_log_scale, exclusion_region,
    genotype, hotspot, target_markers)
print(sampling_set)

N_sim_reps = 100
# gatars(fam, Psi, sampling_set, N_sim_reps = 10)
params_sampling_set = sampling_set$params_sampling_set
sampling_set = sampling_set$sampling_set
weights = NULL
params = params_fn(params_sampling_set, fam, Psi, sampling_set, N_sim_reps, weights)
# ooo = one_experiment_fn(params, calculate_optimized = TRUE)
# ooo$p_value
# inside one_experiment_fn
calculate_optimized = TRUE
theta_init = params$theta_init
g_target = params$g_target
library(Matrix)
rankMatrix(g_target)
```




```{r}
uno_experimento_fn(params, calculate_optimized = TRUE)
```

