---
title: "24-uno_experimento_fn-before-0pt2pt2"
author: ""
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 10, fig.width = 8, tidy=FALSE)
```

`r getwd()`  

"2017-10-13 09:45:10 PDT"

Last knit was `r Sys.time()`

```{r}

N_increments = 50

rho_uni_times_10 = 0:N_increments
alpha_uni_zero = expand.grid(
  B = rho_uni_times_10,
  S = rho_uni_times_10,
  T = rho_uni_times_10)
alpha_uni_zero_sum = apply(alpha_uni_zero, 1, sum)
alpha_uni = alpha_uni_zero[alpha_uni_zero_sum == N_increments, ]
row.names(alpha_uni) = NULL
alpha_uni = alpha_uni/N_increments
alpha_uni

```


```{r}
library(gatars)
keeper = c(1:12, 101:112)
bim = alternative_example$bim
genotype = alternative_example$genotype[keeper, ]
fam = alternative_example$fam[keeper, ]
target_markers = alternative_example$target_markers[c(3, 5)]
Psi = alternative_example$Psi[keeper, keeper]
exclusion_region = alternative_example$exclusion_region
genotype_target_markers = genotype[, target_markers]
set.seed(2)
epsilon_on_log_scale = 0.2
sampling_set = gatars_sampling_set(
    bim, epsilon_on_log_scale, exclusion_region,
    genotype, hotspot, target_markers)
print(sampling_set)

N_sim_reps = 100
# gatars(fam, Psi, sampling_set, N_sim_reps = 10)
params_sampling_set = sampling_set$params_sampling_set
sampling_set = sampling_set$sampling_set
weights = NULL
params = params_fn(params_sampling_set, fam, Psi, sampling_set, N_sim_reps, weights)
tail(params$alpha_uni)

calculate_optimized = TRUE
theta_init = params$theta_init
g_target = params$g_target
library(Matrix)
rankMatrix(g_target)
```




```{r}
uno_experimento_fn(params, calculate_optimized = TRUE)
```


# inside `uno_experimento_fn`


```{r}
adaptive_conf_level = params$adaptive_conf_level
alpha_uni = params$alpha_uni
g_target = params$g_target
MMM = params$MMM
N_sim_reps_interval = params$N_sim_reps_interval
N_sim_reps_limit = params$N_sim_reps_interval
WWW = params$WWW
y_1 = params$yyy
y_2 = params$e_y
Phi = params$Phi
sampling_set = params$sampling_set
test_size = params$test_size

bo = larrys_basic_and_optimized_fn(alpha_uni, g_target, Phi,  WWW, y_1, y_2)
bo
```

# `basic_and_optimized_fn`


This is the only place that `alpha_uni` is used.  (It also is used in `davis_not_lu_depends_on_g_target_fn`, but this function is not called by `uno_experimento_fn`.  (see `23-2017-10-13-foodweb.html`)  

I should set alpha_uni_zero inside params_fn and pass it to here.  

```{r}
rho_uni_times_10 = 0:10
alpha_uni_zero = expand.grid(
  B = rho_uni_times_10,
  S = rho_uni_times_10,
  T = rho_uni_times_10)
alpha_uni_zero_sum = apply(alpha_uni_zero, 1, sum)
alpha_uni = alpha_uni_zero[alpha_uni_zero_sum == 10, ]
row.names(alpha_uni) = NULL
alpha_uni = alpha_uni/10
tail(alpha_uni)



N_increments = 10
rho_uni_times_10 = 0:N_increments
alpha_uni_zero = expand.grid(
  B = rho_uni_times_10,
  S = rho_uni_times_10,
  T = rho_uni_times_10)
alpha_uni_zero_sum = apply(alpha_uni_zero, 1, sum)
alpha_uni = alpha_uni_zero[alpha_uni_zero_sum == N_increments, ]
row.names(alpha_uni) = NULL
alpha_uni = alpha_uni/N_increments
tail(alpha_uni)
```

```{r}
#' @export
larrys_basic_and_optimized_fn = function(alpha_uni, g_target, Phi, WWW, y_1, y_2){
  # ---------------------------------------------------- zzz etc
  zzz_etc = zzz_etc_fn(g_target, Phi, WWW, y_1, y_2)
  zzz = zzz_etc$zzz
  mu_z = zzz_etc$mu_z
  V_z = zzz_etc$V_z
  # -------------------------------------------------- basic_AAA
  basic_ones = alpha_uni[apply(alpha_uni, 1, function(row){
    sum(row == 0) > 1
  }), ]
  MMM = ncol(g_target)
  AAA_basic = lapply(1:nrow(basic_ones), function(jjj){
    alpha = basic_ones[jjj, ]
    AAA = AAA_fn(alpha$B, alpha$S, alpha$T, MMM)
    list(alpha = alpha, AAA = AAA)
  })
  # ------------------------------------------------ df contains 
  # ----------------------B, S, T (the three components of alpha
  # ----------------------- as well as  q, and (nominal) p_value
  df = do.call(rbind, lapply(1:nrow(alpha_uni), function(jjj){
    alpha = alpha_uni[jjj, ]
    AAA = AAA_fn(alpha$B, alpha$S, alpha$T, MMM)
    davies_answer = davies_fn(zzz, mu_z, V_z, AAA)
    cbind(alpha, davies_answer)
  }))
  # ------------------------- basic is a data.frame that contains 
  # ------------------------ the quadratic form q and the p-value 
  # ----------------------- of the three basic statistics B, S, T
  basic = rbind(df[df$B == 1, ],
                df[df$S == 1, ],
                df[df$T == 1, ])
  rownames(basic) =  c("B", "S", "T")
  # --------------------- optimized is a data.frame that contains
  # ------------ the quadratic form q, the nominal p-value, and x
  # ----------------- of the optimized statistics BS, BT, ST, BST
  bs_0 = df[df$B + df$S == 1, ]
  bt_0 = df[df$B + df$T == 1, ]
  st_0 = df[df$S + df$T == 1, ]
  bs = bs_0[which.min(bs_0$p_value), ]
  bt = bt_0[which.min(bt_0$p_value), ]
  st = st_0[which.min(st_0$p_value), ]
  bst = df[which.min(df$p_value), ] 
  optimized = rbind(bs, bt, st, bst)
  xxx = unlist(lapply(optimized$p_value, q_alice_fn))
  optimized$x = xxx
  rownames(optimized) =  c("BS", "BT", "ST", "BST")
  #------------------------------------------------------- output
  p_value_basic = basic$p_value
  names(p_value_basic) = rownames(basic)
  p_value_basic
  
  q_basic = basic$q
  names(q_basic) = rownames(basic)
  q_basic
  
  q_optimized = optimized$q
  names(q_optimized) = rownames(optimized)
  q_optimized
  
  names(xxx) = rownames(optimized)
  list(
    AAA_basic = AAA_basic,
    basic = basic,
    optimized = optimized,
    p_value_basic = p_value_basic,
    q_basic = q_basic,
    q_optimized = q_optimized,
    xxx = xxx)
}
```

