---
title: "04-get-a-teeny-example-for-bim_with_target_exclusion_regions_removed_fn"
author: ""
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 10, fig.width = 8, tidy=FALSE)
```

`r getwd()`  

"2017-11-16 11:51:32 PST"

Last knit was `r Sys.time()`

# `bim_teeny` and `hot_teeny`

```{r}
library(gatars)
#--------------- bim and target_markers
bim = gatars_example$bim
target_markers = c("exm1055449", "exm1562514")
target_markers
bim[bim$snp %in% target_markers, ]
#--------------- independent_segment_containing_first_target_marker
independent_segments_13 = independent_segment_fn(bim, 13, hotspot)
is_this_the_one = sapply(independent_segments_13, function(this){
  any(target_markers %in% this$snp)
})
which(is_this_the_one)
independent_segment_containing_first_target_marker = 
  independent_segments_13[is_this_the_one][[1]]
#--------------- independent_segment_containing_second_target_marker
independent_segments_21 = independent_segment_fn(bim, 21, hotspot)
is_this_the_one = sapply(independent_segments_21, function(this){
  any(target_markers %in% this$snp)
})
which(is_this_the_one)
independent_segment_containing_second_target_marker = 
  independent_segments_21[is_this_the_one][[1]]
#--------------- inside_a_hotspot
inside_a_hotspot = bim[bim$snp == "exm1562489", ]
the_hotspot_line_containing_iah = 
  hotspot[hotspot$chromosome == inside_a_hotspot$chromosome &
          hotspot$start < inside_a_hotspot$bp & inside_a_hotspot$bp < hotspot$end, ]
list(inside_a_hotspot = inside_a_hotspot,
     the_hotspot_line_containing_iah = the_hotspot_line_containing_iah)
#--------------- throw_in_some
throw_in_some = do.call(rbind, list(
  independent_segments_13[[9]],
  independent_segments_21[[10]]))
#--------------- add pretty row.names to make things clearer
row.names(independent_segment_containing_first_target_marker) = 
  paste0("t1_", 1:nrow(independent_segment_containing_first_target_marker))
row.names(independent_segment_containing_second_target_marker) = 
  paste0("t2_", 1:nrow(independent_segment_containing_second_target_marker))
row.names(inside_a_hotspot) = 
  paste0("h_", 1:nrow(inside_a_hotspot))
row.names(throw_in_some) = 
  paste0("throw_", 1:nrow(throw_in_some))
#--------------- bim_baby
bim_baby = do.call(rbind, list(
  independent_segment_containing_first_target_marker,
  independent_segment_containing_second_target_marker,
  inside_a_hotspot,
  throw_in_some))
#--------------- show and tell
list(independent_segment_containing_first_target_marker =
       independent_segment_containing_first_target_marker,
     independent_segment_containing_second_target_marker =
       independent_segment_containing_second_target_marker,
     inside_a_hotspot = inside_a_hotspot,
     bim_baby = bim_baby)
#--------------- a fake params_sampling_set
params_sampling_set = list(
  bim = bim_baby,
  exclusion_region = NULL,
  hotspot = hotspot,
  target_markers = target_markers)
bim_with_target_and_exclusion_regions_removed_fn(params_sampling_set)
```      
