---
title: "06-uno_experimento_fn"
author: ""
output:
  html_document:
    css: ~/Documents/headings.css
    fig_caption: yes
    highlight: default
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document:
    highlight: tango
    number_sections: yes
    pandoc_args: --variable=geometry:margin=0.75in
    toc: no
fontsize: 10pt
---
<A NAME="top"> </A>

```{r global_options, include=FALSE}
require(knitr)
opts_chunk$set(eval = TRUE, echo = TRUE, fig.height = 10, fig.width = 8, tidy=FALSE)
```

`r getwd()`  

"2017-11-17 09:07:47 PST"

Last knit was `r Sys.time()`

```{r}
library(gatars)
# Preparing the data
bim = gatars_example$bim
genotype = gatars_example$genotype
phenotype = gatars_example$phenotype
Psi = gatars_example$Psi
target_markers = gatars_example$target_markers[3:5]

# Call gatars_sampling_set to create sampling_set
sampling_set = gatars_sampling_set(
  bim, epsilon = 0.01, exclusion_region = NULL,
  genotype, hotspot, target_markers)
print(sampling_set)

# Call gatars_test_size using an N_simulated_nulls which is way too small
N_simulated_nulls = 10
library(Matrix)
gatars_test_size(phenotype, Psi, sampling_set, N_simulated_nulls)
```

# inside `gatars_test_size`
```{r}
params_sampling_set = sampling_set$params_sampling_set
sampling_set = sampling_set$sampling_set
alpha_uni_N_increments = 10
weights = NULL
params = params_fn(
    alpha_uni_N_increments, params_sampling_set, phenotype, Psi, sampling_set, N_simulated_nulls, weights)
```


```{r}
ooo = uno_experimento_fn(params, calculate_optimized = TRUE)
```

